name: dart_apex_charts
description: 'A generated Dart API for [APEXCHARTS](https://apexcharts.com/) using dart:js.'
version: '0.2.3'
homepage: 'https://github.com/mdemyanov/dart_apex_charts'
author: 'mdemyanov <mdemyanov@naumen.ru>'

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  build_web_compilers: '>=0.3.6 <0.5.0'
  build_runner: '>=0.8.10 <0.11.0'