name: dart_apex_charts
description: 'A generated Dart API for [APEXCHARTS](https://apexcharts.com/) using dart:js.'
version: '0.2.5'
homepage: 'https://github.com/mdemyanov/dart_apex_charts'
author: 'mdemyanov <mdemyanov@naumen.ru>'

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.0.0
  build_web_compilers: ^0.4.0