name: dart_apex_charts
description: A generated Dart API for [APEXCHARTS](https://apexcharts.com/) using dart:js.
  version: 0.0.1
  homepage: https://www.example.com
  author: mdemyanov <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ^1.0.0
